### ISSUE TITLE
Use pre-commit CI

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/.github#14]
## Detailed Description
I saw this in @peterdudfield's PyTorch-Lightning PR, https://pre-commit.ci/ which applies the fixes from pre-commit automatically to PR requests. This could reduce our development time, as it could fix issues from isort, and black, although not flake8 or pydocstyle.

## Context
Automates one more step of the formatting, etc.

**Comment by JackKelly** [comment]
Nice!  I'm constantly impressed by your and @peterdudfield's knowledge of CI tooling :slightly_smiling_face:

**Comment by peterdudfield** [comment]
amazing, yea go for it - i noticed on PyTorch-Lightning that happening and I was impressed

**Comment by jacobbieker** [comment]
Its live! Working here: https://github.com/openclimatefix/nowcasting_dataloader/pull/39

**Comment by jacobbieker** [comment]
One thing that should be added to all teh `pre-commit-config.yaml` is these lines:

```
ci:
  skip: [pydocstyle, flake8]
```

as that will cause it to skip the two pre-commit checks that it can't fix automatically. I'll update the other repos soon, in that PR I just added it

**Comment by peterdudfield** [comment]
https://results.pre-commit.ci/run/github/375646321/1636102655.-DbmpGNCQA2LSPeft3PTxw

I ran into a problem with this pre-commit for this PR
https://github.com/openclimatefix/nowcasting_dataset/pull/337

perhaps the fix above would do it?
