### ISSUE TITLE
Shall we add python3.10

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/.github#17]
## Detailed Description
Should we add python 3.10 to the pytest running

## Context
Check that is works for users using python 3.10

**Comment by jacobbieker** [comment]
We can run the GH actions with the latest Python version automatically, things broke when I turned it on a few months ago though, so I took it back out. Not sure all the libraries we work with support 3.10

**Comment by peterdudfield** [comment]
Ill close this for the moment then
