### ISSUE TITLE
Upgrade coverage>6.2

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/.github#28]
## Detailed Description
The current bug in coverage 6.3, means we have pinned coverage to less than 6.2

## Context
Good not to pin to an earlier version - lose out on new features

## Possible Implementation
wait for [bug](https://github.com/nedbat/coveragepy/issues/1312) to be fixed, then remove pin

**Comment by jacobbieker** [comment]
I think its been fixed now, so could be good to increase it to the latest one. Also allows setting different infiles then, which would make some configurations easier
