### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/.github#3]
Explain what this repo does, and which files are copied more widely

**Comment by peterdudfield** [comment]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by JackKelly** [comment]
Good idea!

And maybe link to the documentation which links our nowcasting repos together?  See https://github.com/openclimatefix/nowcasting/issues/2
