### ISSUE TITLE
Make docker_release workflow reusable

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/.github#8]
Similar to #6, convert the [`docker_release` workflow from the `nowcasting_api` repo](https://github.com/openclimatefix/nowcasting_api/blob/7c16a11b23e4cd37b575ef423f11f0185e157a8d/.github/workflows/release-docker.yml) to be reusable across repos as well.

Probably also good to copy over the README, [see here](https://github.com/docker/build-push-action/blob/master/docs/advanced/dockerhub-desc.md).

**Comment by peterdudfield** [comment]
Some of this has been done in #26, but would be good to refactor
